NAME = PhoneBook
CC = c++
CFLAGS = -Wall -Wextra -Werror -std=c++98

SRCS = main.cpp \
		Contact.cpp \
		PhoneBook.cpp

OBJS = $(SRCS:.cpp=.o)

HEADERS = Contact.hpp \
		  PhoneBook.hpp
		  
all: $(NAME)
$(NAME): $(OBJS) $(HEADERS)
	$(CC) $(CFLAGS) -o $(NAME) $(OBJS)
clean:
	rm -f $(OBJS)
fclean: clean
	rm -f $(NAME)
re: fclean all
.PHONY: all clean fclean re
